before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq texlive texlive-font-utils texlive-lang-european pandoc latexmk ghostscript

script:
  - make test

deploy:
  provider: pages
  fqgd: smithpeder.github.io/statutter
  local-dir: gh-pages
  skip-cleanup: true
  # github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
